name: publish docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHUBU }}
          password: ${{ secrets.DHUBP}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: neonlabsorg/neon-gnosis-client-gateway:latest
