on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        run: docker build . --file Dockerfile --tag neon-gnosis-client-gateway:latest
      -
        name: Set up Docker Build
        uses: docker/setup-build-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHUBU }}
          password: ${{ secrets.DHUBP }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: neonlabsorg/neon-gnosis-client-gateway:latest
