on: [push]

jobs:
  docker-build-tag-push:
    runs-on: ubuntu-latest
    name: Docker Build, Tag & Publish
    steps:
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          username: ${{ secrets.DHUBU }}
          password: ${{ secrets.DHUBP }}
          context: .
          file: Dockerfile
          repoOwner: neonlabsorg
          repository: neon-gnosis-client-gateway
          tag: latest

