on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        id: buildAndPushImage
        uses: Abhishek-070/Dockerhub-Build-Push@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'neonlabsorg'
          user_name: ${{ secrets.DHUBU }}
          password: ${{ secrets.DHUBP }}
          image_version: 'latest'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
        

  

