on: [push]

jobs:

  push_server_image :

    name : Push Docker image to Docker Hub - server

    runs-on : ubuntu-latest

    permissions:

      packages: write

      contents: read

    steps:

      - uses: actions/checkout@v3

      - name: deploy-container-to-registry

      - uses: slabstech/action-deploy-container-to-registry@v0.0.1

        with:

          docker-username: ${{ secrets.DHUBU }}

          docker-password: ${{ secrets.DHUBP }} 

          github-actor: neonlabsorg

          github-repository: ${{ github.repository }}
      
          project-name: neon-gnosis-client-gateway

          service-name: neon-gnosis-client-gateway
      
          dockerfile-path: ./Dockerfile
